export default {
	c1: { key: "KeyA", midiIn: "" },
	cs1: { key: "KeyS", midiIn: "" },
	d1: { key: "KeyD", midiIn: "" },
	eb1: { key: "KeyF", midiIn: "" },
	e1: { key: "KeyG", midiIn: "" },
	f1: { key: "KeyH", midiIn: "" },
	fs1: { key: "KeyJ", midiIn: "" },
	g1: { key: "KeyK", midiIn: "" },
	gs1: { key: "KeyL", midiIn: "" },
	a1: { key: "Semicolon", midiIn: "" },
	bb1: { key: "Quote", midiIn: "" },
	b1: { key: "Backslash", midiIn: "" },

	c2: { key: "KeyQ", midiIn: "" },
	cs2: { key: "KeyW", midiIn: "" },
	d2: { key: "KeyE", midiIn: "" },
	eb2: { key: "KeyR", midiIn: "" },
	e2: { key: "KeyT", midiIn: "" },
	f2: { key: "KeyY", midiIn: "" },
	fs2: { key: "KeyU", midiIn: "" },
	g2: { key: "KeyI", midiIn: "" },
	gs2: { key: "KeyO", midiIn: "" },
	a2: { key: "KeyP", midiIn: "" },
	bb2: { key: "BracketLeft", midiIn: "" },
	b2: { key: "BracketRight", midiIn: "" },

	c3: { key: "Digit1", midiIn: "" },
	cs3: { key: "Digit2", midiIn: "" },
	d3: { key: "Digit3", midiIn: "" },
	eb3: { key: "Digit4", midiIn: "" },
	e3: { key: "Digit5", midiIn: "" },
	f3: { key: "Digit6", midiIn: "" },
	fs3: { key: "Digit7", midiIn: "" },
	g3: { key: "Digit8", midiIn: "" },
	gs3: { key: "Digit9", midiIn: "" },
	a3: { key: "Digit0", midiIn: "" },
	bb3: { key: "Minus", midiIn: "" },
	b3: { key: "Equal", midiIn: "" },
};
