export default {
	c1: { key: "KeyA", midiIn: 48 },
	cs1: { key: "KeyS", midiIn: 49 },
	d1: { key: "KeyD", midiIn: 50 },
	eb1: { key: "KeyF", midiIn: 51 },
	e1: { key: "KeyG", midiIn: 52 },
	f1: { key: "KeyH", midiIn: 53 },
	fs1: { key: "KeyJ", midiIn: 54 },
	g1: { key: "KeyK", midiIn: 55 },
	gs1: { key: "KeyL", midiIn: 56 },
	a1: { key: "Semicolon", midiIn: 57 },
	bb1: { key: "Quote", midiIn: 58 },
	b1: { key: "Backslash", midiIn: 59 },

	c2: { key: "KeyQ", midiIn: 60 },
	cs2: { key: "KeyW", midiIn: 61 },
	d2: { key: "KeyE", midiIn: 62 },
	eb2: { key: "KeyR", midiIn: 63 },
	e2: { key: "KeyT", midiIn: 64 },
	f2: { key: "KeyY", midiIn: 65 },
	fs2: { key: "KeyU", midiIn: 66 },
	g2: { key: "KeyI", midiIn: 67 },
	gs2: { key: "KeyO", midiIn: 68 },
	a2: { key: "KeyP", midiIn: 69 },
	bb2: { key: "BracketLeft", midiIn: 70 },
	b2: { key: "BracketRight", midiIn: 71 },

	c3: { key: "Digit1", midiIn: 72 },
	cs3: { key: "Digit2", midiIn: 73 },
	d3: { key: "Digit3", midiIn: 74 },
	eb3: { key: "Digit4", midiIn: 75 },
	e3: { key: "Digit5", midiIn: 76 },
	f3: { key: "Digit6", midiIn: 77 },
	fs3: { key: "Digit7", midiIn: 78 },
	g3: { key: "Digit8", midiIn: 79 },
	gs3: { key: "Digit9", midiIn: 80 },
	a3: { key: "Digit0", midiIn: 81 },
	bb3: { key: "Minus", midiIn: 82 },
	b3: { key: "Equal", midiIn: 83 },
};
